// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlrNagsi7mOjBR9UvGL-IPqx5RVKIQVpw',
    appId: '1:977896943604:web:8fc7dcade8a472310193a1',
    messagingSenderId: '977896943604',
    projectId: 'travel-booking-app-aef05',
    authDomain: 'travel-booking-app-aef05.firebaseapp.com',
    storageBucket: 'travel-booking-app-aef05.firebasestorage.app',
    measurementId: 'G-BM9X9DKMQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_XArTHcOlYJPm196xY78YL8AroD72R4A',
    appId: '1:977896943604:android:cd02369a3c8d1ded0193a1',
    messagingSenderId: '977896943604',
    projectId: 'travel-booking-app-aef05',
    storageBucket: 'travel-booking-app-aef05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1563k6n2OJXZvun-nmySZKoxoC66M3DU',
    appId: '1:977896943604:ios:e86767a430c64e7b0193a1',
    messagingSenderId: '977896943604',
    projectId: 'travel-booking-app-aef05',
    storageBucket: 'travel-booking-app-aef05.firebasestorage.app',
    iosBundleId: 'com.example.travelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1563k6n2OJXZvun-nmySZKoxoC66M3DU',
    appId: '1:977896943604:ios:e86767a430c64e7b0193a1',
    messagingSenderId: '977896943604',
    projectId: 'travel-booking-app-aef05',
    storageBucket: 'travel-booking-app-aef05.firebasestorage.app',
    iosBundleId: 'com.example.travelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlrNagsi7mOjBR9UvGL-IPqx5RVKIQVpw',
    appId: '1:977896943604:web:34c741ffb61270530193a1',
    messagingSenderId: '977896943604',
    projectId: 'travel-booking-app-aef05',
    authDomain: 'travel-booking-app-aef05.firebaseapp.com',
    storageBucket: 'travel-booking-app-aef05.firebasestorage.app',
    measurementId: 'G-EC7LPNMLWL',
  );

}